return {
    {
        "mfussenegger/nvim-dap",
        version = "0.10.0",
        config = function()
            require("plugins.config.dap")
        end,
        keys = {
            {
                "<leader>db",
                function()
                    require("dap").toggle_breakpoint()
                end,
            },
            {
                "<leader>dc",
                function()
                    require("plugins.config.dap").continue()
                end,
            },
            {
                "<F5>",
                function()
                    require("plugins.config.dap").continue()
                end,
            },
            {
                "<leader>dn",
                function()
                    require("dap").step_over()
                end,
            },
            {
                "<leader>di",
                function()
                    require("dap").step_into()
                end,
            },
            {
                "<leader>do",
                function()
                    require("dap").step_out()
                end,
            },
            {
                "<leader>dd",
                function()
                    require("dap").down()
                end,
            },
            {
                "<leader>dl",
                function()
                    require("dap").run_last()
                end,
            },
            {
                "<leader>du",
                function()
                    require("dap").up()
                end,
            },
            {
                "<leader>dg",
                function()
                    require("dap").repl.open()
                end,
            },
            {
                "<leader>dr",
                function()
                    require("dap").restart()
                end,
            },
            {
                "<leader>da",
                function()
                    require("dap").terminate()
                end,
            },
            {
                "<leader>dh",
                function()
                    require("dap.ui.widgets").hover()
                end,
            },
            {
                "<leader>dp",
                function()
                    require("dap.ui.widgets").preview()
                end,
            },
            {
                "<leader>df",
                function()
                    local widgets = require("dap.ui.widgets")
                    widgets.centered_float(widgets.frames)
                end,
            },
            {
                "<leader>ds",
                function()
                    local widgets = require("dap.ui.widgets")
                    widgets.centered_float(widgets.scopes)
                end,
            },
        },
    },
    {
        "rcarriga/nvim-dap-ui",
        dependencies = { "mfussenegger/nvim-dap", "nvim-neotest/nvim-nio" },
        config = function()
            require("plugins.config.dapui")
        end,
        keys = {
            {
                "<leader>dt",
                function()
                    require("dapui").toggle()
                end,
            },
        }
    }
}
