unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# clear buffer
# bind-key C-k clear-history

#
set-option -g mouse off

# easier numbers to type
set-option -g base-index 0
set-option -g pane-base-index 0
set-option -g renumber-windows on

# may conflict with kitty
set -s set-clipboard on

set -g default-shell /bin/zsh
set -g pane-border-status off

set-option -ga terminal-overrides ",$TERM:RGB"

################################################################################
# clear buffer
bind-key C-c clear-history

################################################################################
# Copy/Paste
# taken from: https://www.seanh.cc/2020/12/27/copy-and-paste-in-tmux/

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xsel -i -b'

################################################################################
# status bar
bind-key b set-option -g status
bind-key c-b set-option -g status

set -g status-bg default
set -g status-fg colour2
# set -g window-status-format "#I:#W"
set -g window-status-format "#W"
set -g window-status-current-format "#[bg=colour2,fg=black] #W #[bg=default,fg=colour2]"


################################################################################
# tpm plugins

set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'danyim/tmux-remote'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'nhdaly/tmux-better-mouse-mode'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-resurrect'

################################################################################
# plugin config

# set -g @continuum-restore 'on'
# set -g @resurrect-strategy-nvim 'session'
set -g @yank_selection 'clipboard'
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'
set -g @yank_action 'copy-pipe-and-cancel' # 'copy-pipe-no-clear'

################################################################################
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
